abstract: Base class for working with Perl distributions
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Spec: 0.80
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Module-Extract
no_index: 
  directory: 
    - inc
    - t
requires: 
  Archive::Extract: 0.12
  Carp: 0
  File::Path: 1.06
  File::Temp: 0.17
version: 0.01
